version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/app/docs
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_URL=postgresql://postgres:postgres@postgres:5432/ecommerce
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    depends_on:
      - postgres
      - chromadb

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  loader:
    build:
      context: .
      dockerfile: Dockerfile.loader
    depends_on:
      - postgres

  chromadb:
    image: ghcr.io/chroma-core/chroma:1.0.15
    container_name: chromadb
    ports:
      - "8001:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma-data
    volumes:
      - chroma-data:/chroma-data

  ui:
    build:
      context: https://github.com/haroonob/react-ui-for-conversational-bi.git
      dockerfile: Dockerfile
    ports:
      - "8080:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api

volumes:
  pgdata:
  chroma-data:
