FROM python:3.10-slim

WORKDIR /app

COPY app /app/app
COPY docs /app/docs
COPY README.md requirements.txt ./

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
